module.exports = [
  'Ethereum',
  'Uniswap',
  'Binance_Smart_Chain',
  'Trader_Joe',
  'Aave',
  'SushiSwap',
  'Compound',
  'Bitcoin',
  'Balancer',
  'Terraswap',
  'MakerDAO',
  'Avalanche',
  'Abracadabra_money',
  'SpookySwap',
  'Quickswap',
]